### ISSUE TITLE
Support for Terraform 0.12.x

### ISSUE THREAD

**Issue by laurmurclar** [laurmurclar/datadog-to-terraform#22]
Not sure what needs to be done here, but marking it so I don't forget

**Comment by daroga0002** [comment]
to make `datadog_monitor` compatible with terraform 0.12 and later you must correct code generation for blocks like here:
https://github.com/laurmurclar/datadog-to-terraform/blob/8ed73205a00300d03ae48b850d34ae264e445172/examples/monitor.tf#L24-L26

in general this should be rendered with additional `=`:
```
thresholds = { 
   critical = 50 
 } 
```

same for `silenced` block.

As per https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor

**Comment by laurmurclar** [comment]
@daroga0002 thank you! If you're interested in making the changes, feel free. It might be a while before I have time to work on them but I can certainly review pull requests :)

**Comment by laurmurclar** [comment]
This should be done once v3.4 is published (it's been submitted to the store but is under review). Let me know if there's any issues with it once it's out - feel free to re-open this issue.
