### ISSUE TITLE
Support Datadog Timeboards

### ISSUE THREAD

**Issue by joeblubaugh** [laurmurclar/datadog-to-terraform#24]
**Is your feature request related to a problem? Please describe.**
In addition to monitor conversion, support Timeboard conversion.

**Describe the solution you'd like**
Automatically detect monitor or timeboard format and output appropriate terraform.

**Comment by laurmurclar** [comment]
Hey @joeblubaugh, thanks! This seems really useful. If you (or anyone else) would like to work on it, feel free - I probably won't have time in the next few weeks but can definitely review PRs :)

**Comment by joeblubaugh** [comment]
After posting this I gathered some more information:
1. The Hashicorp Provider uses different names than the Datadog API in several places. That will require some translation in any converters.
2. The Datadog Dashboards API is preferred over the Timeboards API now. I think supporting timeboards as their own feature is likely to remain very useful, so I'd still support doing this particular piece of work.

**Comment by laurmurclar** [comment]
Awesome, thank you! Sorry for the delay in getting back to you, I've been on holidays. Will take a look now

**Comment by laurmurclar** [comment]
This feature is now released 🎉 Thanks again. If anyone spots any new bugs or has feedback on this feature, please open a new issue :)
