### ISSUE TITLE
Conversion for "template_variable_presets" not found

### ISSUE THREAD

**Issue by edwdev** [laurmurclar/datadog-to-terraform#30]
Conversion for "template_variable_presets" not found

1. Copy the following json output from Datadog:

`{"title":"Kafka","description":"","widgets":[{"id":474085478675668,"definition":{"type":"query_value","requests":[{"q":"sum:kafka.replication.active_controller_count{$Cluster}","aggregator":"last","conditional_formats":[{"comparator":"<","value":1,"palette":"red_on_white"},{"comparator":">=","value":1,"palette":"green_on_white"}]}],"title":"Active Controllers","autoscale":true,"precision":0}},{"id":2410444471924698,"definition":{"type":"timeseries","requests":[{"q":"avg:kafka.replication.offline_partitions_count{$Cluster} by {brokerid,host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Offline Partitions","show_legend":false,"legend_size":"0"}},{"id":7173053017000254,"definition":{"type":"timeseries","requests":[{"q":"sum:kafka.replication.under_replicated_partitions{$Cluster} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Under Replicated Partitions","show_legend":false,"legend_size":"0"}},{"id":5067666987827614,"definition":{"type":"timeseries","requests":[{"q":"100-avg:system.cpu.idle{$Cluster} by {host,brokerid}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU","show_legend":false,"legend_size":"0"}},{"id":4510232294941812,"definition":{"type":"timeseries","requests":[{"q":"avg:system.net.tcp6.established{$Cluster} by {brokerid,host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Network Connections","show_legend":false,"legend_size":"0"}},{"id":3535194655711416,"definition":{"type":"timeseries","requests":[{"q":"top((sum:kafka.net.bytes_out.rate{$Cluster} by {host,brokerid}/sum:system.net.bytes_sent{$Cluster,device:eth1} by {host,brokerid})*100,10,'last','desc')","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Overhead traffic percentage (output)","show_legend":false,"legend_size":"0"}},{"id":1623948339331226,"definition":{"type":"timeseries","requests":[{"q":"sum:kafka.messages_in.rate{$Cluster}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Messsage In Rate ","show_legend":false,"legend_size":"0"}},{"id":8318842337414129,"definition":{"type":"timeseries","requests":[{"q":"top(avg:kafka.topics.messages_in.rate{$Cluster} by {host,brokerid}, 10, 'mean', 'desc')","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Messages in per Broker","show_legend":false,"legend_size":"0"}},{"id":1608970740040038,"definition":{"type":"timeseries","requests":[{"q":"top(avg:kafka.topics.messages_in.rate{$Cluster} by {host,topic,brokerid}, 10, 'mean', 'desc')","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Messages in per Broker per Topic","show_legend":false,"legend_size":"0"}},{"id":4838996117696610,"definition":{"type":"timeseries","requests":[{"q":"per_minute(sum:jvm.gc.cms.count{$Cluster} by {brokerid,host})","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"JVM GC per minute","show_legend":false,"legend_size":"0"}},{"id":7130496428765594,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.gc.minor_collection_time{$Cluster} by {host,brokerid}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"sum:jvm.gc.minor_collection_count{$Cluster} by {host,brokerid}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"JVM Minor GC  time and count","show_legend":false,"legend_size":"0"}},{"id":839094311219598,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.heap_memory{$Cluster} by {brokerid,host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_max{$Cluster} by {brokerid,host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"JVM Heap Memory Used/Max","show_legend":false,"legend_size":"0"}},{"id":1624807156261464,"definition":{"type":"timeseries","requests":[{"q":"avg:kafka.net.handler.avg.idle.pct.rate{$Cluster} by {brokerid,host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Available Network Threads","show_legend":false,"legend_size":"0"}},{"id":5767422523541078,"definition":{"type":"timeseries","requests":[{"q":"avg:kafka.request.handler.avg.idle.pct.rate{$Cluster} by {brokerid,host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Available Request handler (IO) threads ","show_legend":false,"legend_size":"0"}},{"id":4162215556109631,"definition":{"type":"toplist","requests":[{"q":"top(avg:kafka.topics.messages_in.rate{$Cluster} by {topic,brokerid,host}, 10, 'sum', 'desc')"}],"title":"Avg of kafka.topics.messages_in.rate over $cluster by topic,brokerid,host"}},{"id":5310444385871147,"definition":{"type":"toplist","requests":[{"q":"top(avg:kafka.topics.net.bytes_in.rate{$Cluster} by {topic,brokerid,host}, 10, 'sum', 'desc')"}],"title":"Avg of kafka.topics.net.bytes_in.rate over $cluster by topic,brokerid,host"}},{"id":2245277047199664,"definition":{"type":"timeseries","requests":[{"q":"avg:kafka.Partition_Rebalance_Count{$Cluster} by {cluster}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"label":"","scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Avg of kafka.Partition_Rebalance_Count over $cluster by cluster","show_legend":false,"legend_size":"0"}}],"template_variables":[{"name":"Cluster","default":"*","prefix":"Cluster"}],"layout_type":"ordered","is_read_only":false,"notify_list":[],"template_variable_presets":[{"name":"GP","template_variables":[]},{"name":"PD","template_variables":[{"name":"Cluster","value":"kafkabroker-pd"}]}],"id":"8q9-ni5-d7z"}`

2. Clicking convert, gives the following error:
Conversion for "template_variable_presets" not found

**Comment by laurmurclar** [comment]
Thanks for flagging this! Will try get a fix out in the next couple of days :)

**Comment by laurmurclar** [comment]
I've submitted the fix to the addon stores for review - it might take a couple of hours/days to be published but this fix is merged :) Thanks again for taking the time to create the issue

**Comment by edwdev** [comment]
Thanks so much for the quick fix!
