### ISSUE TITLE
Terraform apply fails due to blocks being defined as arguments during conversion from json

### ISSUE THREAD

**Issue by ayapejian-centeredge** [laurmurclar/datadog-to-terraform#34]
**Describe the bug**
Screenboard or Timeboard JSON converted into Terraform/HCL fails `terraform apply` due to incorrect format of `style`, `yaxis`, `custom_links` attribute blocks (maybe others).  I believe this is a more recent change in terraform, using terraform `13.5` at the moment.

**To Reproduce**
1. Create a dashboard with a time series graph
2. Export json and paste into extension
3. Put into terraform file and apply
4. See failures similiar to below:

```
Error: Unsupported argument

  on datadog.tf line 40, in resource "datadog_dashboard" "ay-dashboard-test":
  40:       yaxis = {

An argument named "yaxis" is not expected here. Did you mean to define a block
of type "yaxis"?


Error: Unsupported argument

  on datadog.tf line 67, in resource "datadog_dashboard" "ay-dashboard-test":
  67:         style = {

An argument named "style" is not expected here. Did you mean to define a block
of type "style"?
```

**Expected behavior**
Terraform apply should create dashboard

**System info (please complete the following information):**
 - Browser: Happened on both Firefox and Chrome extensions
 - Version: 3.4.1
 - Terraform version: 13.5

**Additional context**
As a workaround search and replace in the converted terraform output
* `yaxis = {` to `yaxis {`
* `style = {` to `style {`
* `custom_links` I just deleted since we aren't using them

**Comment by laurmurclar** [comment]
Sorry @ayapejian-centeredge, I completely missed this issue! Will take a look and hopefully get a fix out in the next couple of days

**Comment by laurmurclar** [comment]
I've merged the fix for this, but won't release the next version until I've fixed another bug - probably tomorrow
