### ISSUE TITLE
Omit deprecated param 'logset'

### ISSUE THREAD

**Issue by flavio-cadete-cko** [laurmurclar/datadog-to-terraform#53]
Don't have permissions to create a branch:

app\dashboard-converter.js :
`logset: (_) => "", // 2.23.0 deprecated, see docs for widget.log_stream_definition`

examples\screenboard.json :
 ```
{
      "id": 1177803908467722,
      "layout": {
        "x": 968,
        "y": -242,
        "width": 33,
        "height": 21
      },
      "definition": {
        "title": "Plugins",
        "title_size": "13",
        "title_align": "left",
        "type": "log_stream",
        "logset": "",
        "indexes": [],
        "query": "$dd_env $app_group status:(error OR emergency)",
        "sort": {
          "column": "service",
          "order": "desc"
        },
        "show_date_column": true,
        "show_message_column": true,
        "message_display": "expanded-md"
      }
```

**Comment by laurmurclar** [comment]
Hey @flavio-cadete-cko, I won't have time to get to this today. You can fork the repo and make a pull request back to the main branch of this one. If you're not familiar with that workflow, google "forking workflow github" they have a good description of how to do it in their docs.
