### ISSUE TITLE
Add Monitor - "classification" property

### ISSUE THREAD

**Issue by flavio-cadete-cko** [laurmurclar/datadog-to-terraform#58]
New property "classification" for every monitor
values e.g. 'log', 'metric', ...

**Comment by flavio-cadete-cko** [comment]
After: https://github.com/DataDog/terraform-provider-datadog/issues/1039

**Comment by laurmurclar** [comment]
From what I can see, `classification` isn't a field on `datadog_monitor` yet. From the issue you linked, it looks like a decision on how this should map (or whether it even should be a key at all) hasn't even been made yet, so I'm going to close this issue. There's not much point having an issue which isn't actionable or capturing context, I think it just adds confusion. 

If `classification` is added to the Datadog provider, feel free to reopen this.
