### ISSUE TITLE
Cannot convert new fields

### ISSUE THREAD

**Issue by OsamaSBCrea** [laurmurclar/datadog-to-terraform#90]
**Describe the bug**
The plugin cannot convert these fields in DD monitor JSON:
- `restriction_query`
- `on_missing_data`
- `restricted_roles`

**To Reproduce**
```json
{
	"id": 10000000000,
	"name": "Console: A high error rate",
	"type": "rum alert",
	"query": "rum(\"-env:dev @error.source:(console OR source) @type:error\").rollup(\"count\").last(\"15m\") > 3",
	"message": "A high error rate",
	"tags": [
		"env:prod"
	],
	"options": {
		"thresholds": {
			"critical": 3
		},
		"enable_logs_sample": false,
		"notify_audit": false,
		"restriction_query": null,
		"on_missing_data": "default",
		"include_tags": false,
		"new_host_delay": 300,
		"groupby_simple_monitor": false,
		"silenced": {}
	},
	"priority": 2,
	"restricted_roles": [
		"ROLE_ID"
	]
}
```

**Screenshots**
<img width="523" alt="image" src="https://user-images.githubusercontent.com/34233324/227917047-c4098b56-f4ed-4ded-bab2-1f0d082eb444.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/34233324/227917113-8f09187e-b9ff-48dd-8dc0-9e78c95b618f.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/34233324/227917219-20626c4e-9ba4-4b7b-aa57-508a9c951caf.png">

**Comment by vigohe** [comment]
@OsamaSBCrea from what I see only `on_missing_data`, is not supported in the terraform provider

https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor

**Comment by asfaltboy** [comment]
I am seeing the same error with this in the bottom of my browser addon

```
❗️Can't convert key 'restriction_query'
```

**Comment by laurmurclar** [comment]
Oops, this got auto-closed via closing https://github.com/laurmurclar/datadog-to-terraform/pull/91. That PR adds `on_missing_data`, `renotify_statuses` and `restricted_roles`. I'll add `restriction_query` now myself.

**Comment by laurmurclar** [comment]
Actually, `restriction_query` doesn't seem to be supported by the provider - at least, I can't find it in the [docs](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor) and there seems to be a [feature request open for it](https://github.com/DataDog/terraform-provider-datadog/issues/1217). It doesn't make sense to add it here until it's supported, so I'll just release the other 3 today.
